function(import_subdirectory)
    set(options)
    set(oneValueArgs SUB_NAME)
    set(multiValueArgs SOURCES TARGET_INCLUDE LINKLIB)
    cmake_parse_arguments(FUNC "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    # message("import - " ${FUNC_SUB_NAME})
    # message("src - " ${FUNC_SOURCES})
    # message("target_include - " ${FUNC_TARGET_INCLUDE})
    add_library(${FUNC_SUB_NAME} ${FUNC_SOURCES})
    if(NOT FUNC_LINKLIB)
        message("")
    else()
        target_link_libraries(${FUNC_SUB_NAME} ${FUNC_LINKLIB})
    endif()
    
    target_include_directories(${FUNC_SUB_NAME} PUBLIC ${FUNC_TARGET_INCLUDE})
endfunction()

function(import_executable)
    set(options)
    set(oneValueArgs SUB_NAME)
    set(multiValueArgs SOURCES TARGET_INCLUDE LINKLIB)
    cmake_parse_arguments(FUNC "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    # message("import - " ${FUNC_SUB_NAME})
    # message("src - " ${FUNC_SOURCES})
    # message("target_include - " ${FUNC_TARGET_INCLUDE})
    add_executable(${FUNC_SUB_NAME} ${FUNC_SOURCES})
    if(NOT FUNC_LINKLIB)
        message("")
    else()
        target_link_libraries(${FUNC_SUB_NAME} ${FUNC_LINKLIB})
    endif()
    
    target_include_directories(${FUNC_SUB_NAME} PUBLIC ${FUNC_TARGET_INCLUDE})
endfunction()